os: linux
arch: arm64-graviton2
group: edge
language: ruby
cache: bundler
gemfile: Gemfile
branches:
  only:
  - master
rvm:
- 2.6
notifications:
  email:
    recipients:
    - arran@madeslowly.co.uk
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_f355d508fe95_key -iv $encrypted_f355d508fe95_iv
  -in bluehost.enc -out /tmp/bluehost -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/bluehost
- ssh-add /tmp/bluehost
script:
- bundle update
- bundle install
- JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet /_site/ ydnwpmmy@ydn.wpm.mybluehost.me:public_html/test
  on:
    branch: master
