jekyll_info: '  * jekyll (4.2.0)
  * jekyll-autoprefixer (1.0.2)
  * jekyll-feed (0.15.1)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (2.1.0)
  * jekyll-sitemap (1.4.0)
  * jekyll-target-blank (2.0.0)
  * jekyll-watch (2.2.1)' 
theme_info: '' 
